<?php
echo "<table  width='100%'    border='0' ><tr><td width='180' style='text-align: center; vertical-align: middle;  padding: 0.5em; background:white;'> <img  alt='Valstybinis patentų biuras' src='imgs/vpb_logo.jpg' /> 



</td>
<td  style='background: url(imgs/hed.jpg) no-repeat; color:  brown; background-color: white; vertical-align:  middle; padding: 0.5em;'> 
<p style=' font-size: 150%; font-weight: bold;'>Telefonai</p>

<p>
Kalvarijų g. 3, LT-09310 Vilnius <br />
Kodas 188708943<br />
Informacija tel. (8 5) 278 02 90, faksas (8 5) 275 0723<br />
El. paštas info@vpb.gov.lt
</p>



</td></tr></table>\n";

?>
